"""Markup-level tests for ``kb_graph.svg``.

One section per clause of the row's done-condition.

**The golden's index is built at test time, never committed.** The
committed ``mini-kb`` fixture is copied to a temp directory, ``refresh`` runs
over the copy, and the sheet is rendered from what it emitted; only the ``.svg``
is committed. A committed ``.index/`` would be a derived artifact in the tree
with no freshness gate — the drift surface the canonical-direction rule exists
to prevent — and it could go stale against the fixture it derives from. Built
this way it cannot, and a change to an emitter's record shape surfaces as a
golden diff instead of hiding behind a frozen copy. :func:`render_mini_kb_golden`
and :func:`write_mini_kb_golden` are that helper, and ``just regenerate-mini-kb-golden``
runs through them so the recipe and this suite build the index the same way.

**The copy must carry the fixture's ``CLAUDE.md``** or the framework nodes it
declares never appear — the fixture hosts its invariants and axioms there, and a
golden rendered without them would be a smaller picture that still reproduced
itself forever.

The synthetic fixtures cover what ``mini-kb`` cannot: it carries no empty
``canonical_anchor`` and no hostile title, so those two are built here.
"""

import ast
import os
import re
import shutil
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET
from collections.abc import Iterable
from fractions import Fraction
from pathlib import Path, PurePosixPath

import pytest

from kb_tools import kb_schema
from kb_tools.kb_cmd import index as kb_index
from kb_tools.kb_graph import layout, model, style, svg

_TESTS = Path(__file__).resolve().parent
#: The directory holding the ``kb_tools`` package — the refresh run's PYTHONPATH.
_PKG_PARENT = _TESTS.parents[1]
_PACKAGE = _PKG_PARENT / "kb_tools" / "kb_graph"
_MINI_KB = _TESTS / "fixtures" / "mini-kb"

#: The committed golden. Regenerated by :func:`write_mini_kb_golden`, never
#: hand-edited: a hand-authored golden is a byte-fidelity expectation placed on
#: inference, and this document is exactly the artifact that would expose it.
MINI_KB_GOLDEN = _TESTS / "fixtures" / "graph" / "mini-kb.svg"

#: Where the golden's links point, as repo-relative POSIX paths: from the
#: golden's own directory to the committed fixture it describes. Written as
#: paths rather than resolved absolutes so no machine-local prefix can reach an
#: output position — the sheet the test renders is built over a temp copy,
#: and a link into that copy would be a different document on every run.
_GOLDEN_LINK_BASE = svg.relative_link_base(
    kb_root=PurePosixPath("kb_tools/tests/fixtures/mini-kb"),
    sheet_dir=PurePosixPath("kb_tools/tests/fixtures/graph"),
)


# ---------------------------------------------------------------------------
# The golden-fixture helper
# ---------------------------------------------------------------------------


def _refresh(kb_root: Path) -> subprocess.CompletedProcess:
    """Run the refresh target's module over ``kb_root``, as ``test_refresh_index`` does."""
    return subprocess.run(
        [sys.executable, "-m", "kb_tools.refresh_kb_metadata", "--kb-root", str(kb_root)],
        cwd=_PKG_PARENT,
        env={**os.environ, "PYTHONPATH": str(_PKG_PARENT), "PYTHONDONTWRITEBYTECODE": "1"},
        capture_output=True,
        text=True,
        check=False,
    )


def render_mini_kb_golden() -> str:
    """The ``mini-kb`` sheet, from an index built over a temp copy of the fixture.

    The committed fixture is never mutated and the index it derives is never
    committed. The copy is a whole-tree copy, so it carries the fixture's
    ``CLAUDE.md`` — the framework nodes' authored home.
    """
    with tempfile.TemporaryDirectory() as workspace:
        kb_root = Path(workspace) / _MINI_KB.name
        shutil.copytree(_MINI_KB, kb_root)
        result = _refresh(kb_root)
        if result.returncode != 0:
            raise RuntimeError(f"refresh over the mini-kb copy failed:\n{result.stdout}\n{result.stderr}")

        index = kb_index.load(kb_root / ".index")
        graph = model.build_graph(nodes=index.all_nodes, edges=index.all_depends_on_edges)
        return svg.render(layout.place(graph), link_base=_GOLDEN_LINK_BASE)


def write_mini_kb_golden() -> Path:
    """Regenerate the committed golden. The one writer, following the write discipline."""
    MINI_KB_GOLDEN.parent.mkdir(parents=True, exist_ok=True)
    MINI_KB_GOLDEN.write_text(render_mini_kb_golden(), encoding="utf-8", newline="\n")
    return MINI_KB_GOLDEN


@pytest.fixture(scope="module")
def mini_kb_renders() -> tuple[str, str]:
    """Two independent renders of the fixture — copy, refresh and all.

    Module-scoped: each render pays for a full refresh, and every question below
    reads the same pair rather than buying a run apiece.
    """
    return render_mini_kb_golden(), render_mini_kb_golden()


# ---------------------------------------------------------------------------
# Record and graph builders for the synthetic fixtures
# ---------------------------------------------------------------------------


def _claim(cid: str, *, title: str = "A claim", anchor: str = "a-claim", band: str = "ok-to-build") -> kb_index.Claim:
    return kb_index.Claim(
        node_type="claim",
        id=cid,
        title=title,
        canonical_path="vol1/topic/leaf.md",
        canonical_anchor=anchor,
        confidence=None,
        solidity=None,
        build_status=None,
        build_band=band,
        rationale="",
        depends_on_count=0,
        strengthen_by_count=0,
        citation_count=0,
    )


def _support(sid: str) -> kb_index.SupportNode:
    return kb_index.SupportNode(
        node_type="support",
        id=sid,
        title="A support",
        canonical_path="vol1/topic/sup.md",
        canonical_anchor="a-support",
        quality=None,
        solidity=None,
        build_band="do-not-build",
    )


def _experiment(eid: str) -> kb_index.ExperimentNode:
    return kb_index.ExperimentNode(
        node_type="experiment",
        id=eid,
        title="An experiment",
        canonical_path="vol1/topic/exp.md",
        canonical_anchor="an-experiment",
        status="run",
    )


def _framework(fid: str, node_type: str = "invariant") -> kb_index.FrameworkNode:
    return kb_index.FrameworkNode(
        node_type=node_type,
        id=fid,
        title="A framework rule",
        canonical_path="CLAUDE.md",
        canonical_anchor=fid.lower(),
    )


def _edge(source: str, target: str, **overrides) -> kb_index.DependsOnEdge:
    fields = {
        "source": source,
        "target": target,
        "target_kind": "claim",
        "target_solidity_recorded": None,
        "context": None,
        "relation": "depends",
        "strength": None,
        "fraction": None,
    }
    fields.update(overrides)
    return kb_index.DependsOnEdge(**fields)


def _sheet(nodes: Iterable[kb_index.GraphNode], edges: Iterable[kb_index.DependsOnEdge] = ()) -> layout.Sheet:
    return layout.place(model.build_graph(nodes=list(nodes), edges=list(edges)))


def _render(nodes, edges=(), *, link_base: str = "kb-root", foreign: Iterable[str] = ()) -> str:
    return svg.render(_sheet(nodes, edges), link_base=link_base, foreign=tuple(foreign))


# ---------------------------------------------------------------------------
# Reading a rendered document back
# ---------------------------------------------------------------------------


def _local(tag: str) -> str:
    """The tag without the namespace the parser resolves ``xmlns`` into."""
    return tag.rpartition("}")[2]


def _by_local(root: ET.Element, name: str) -> list[ET.Element]:
    return [element for element in root.iter() if _local(element.tag) == name]


def _node_groups(root: ET.Element) -> dict[str, ET.Element]:
    """Every node group, keyed by the id its first label line carries."""
    groups = [element for element in _by_local(root, "g") if element.get("class") == "node"]
    return {_by_local(group, "text")[0].text.split(" ")[0]: group for group in groups}


def _edge_lines(root: ET.Element) -> dict[tuple[str, str], ET.Element]:
    """Every stroke, keyed by the pair its tooltip head names.

    One ``polyline`` per edge however many layers it spans: an edge crossing
    layers is routed through a dummy in each, and the whole chain is one
    element.
    """
    out = {}
    for line in _by_local(root, "polyline"):
        head = _by_local(line, "title")[0].text.split(" — ")[0]
        source, _, target = head.partition(" → ")
        out[(source, target)] = line
    return out


def _hrefs(root: ET.Element) -> dict[str, str]:
    """Every link target, keyed by the id of the node group it wraps."""
    out = {}
    for anchor in _by_local(root, "a"):
        group = list(anchor)[0]
        out[_by_local(group, "text")[0].text.split(" ")[0]] = anchor.get("href")
    return out


# ---------------------------------------------------------------------------
# The golden: rendered from a temp copy, twice in a row, byte-identically
# ---------------------------------------------------------------------------


def test_two_renders_over_two_temp_copies_are_byte_identical(mini_kb_renders: tuple[str, str]) -> None:
    """Copy, refresh, render — twice, end to end. No temp path reaches the sheet."""
    first, second = mini_kb_renders
    assert first == second


def test_the_render_reproduces_the_committed_golden(mini_kb_renders: tuple[str, str]) -> None:
    assert mini_kb_renders[0] == MINI_KB_GOLDEN.read_text(encoding="utf-8")


def test_the_golden_is_the_document_and_not_an_empty_one() -> None:
    """A golden regenerated from a renderer that drew nothing would compare against
    itself forever and assert nothing at all. The fixture's own shape is the guard:
    all four node types, the two edge classes the real corpus does not exercise, and
    the framework nodes that only arrive if the copy carried ``CLAUDE.md``."""
    root = ET.fromstring(MINI_KB_GOLDEN.read_text(encoding="utf-8"))
    groups = _node_groups(root)

    assert len(groups) == 32
    assert len(_edge_lines(root)) == 18
    assert any(node_id.startswith("INVARIANT-") for node_id in groups), "the copy lost kb-root/CLAUDE.md"
    assert any(node_id.startswith("axiom-") for node_id in groups)
    assert any(node_id.startswith("sup-") for node_id in groups)
    assert any(node_id.startswith("exp-") for node_id in groups)
    assert _by_local(root, "path"), "the fixture crosses; the arcs are part of what the golden pins"


def test_the_golden_ends_in_exactly_one_newline_and_opens_with_the_pinned_declaration() -> None:
    """The pinned declaration and the single trailing newline, checked on the
    committed bytes rather than on the renderer's return value."""
    text = MINI_KB_GOLDEN.read_text(encoding="utf-8")
    assert text.startswith('<?xml version="1.0" encoding="utf-8"?>\n')
    assert text.endswith(">\n") and not text.endswith("\n\n")


# ---------------------------------------------------------------------------
# Well-formedness and the hostile title
# ---------------------------------------------------------------------------


_HOSTILE_TITLE = "Proposition <4.3> & \"the\" 'β' — $\\beta$ ≤ ½ … ✓"


def test_every_golden_parses_as_xml() -> None:
    assert ET.fromstring(MINI_KB_GOLDEN.read_text(encoding="utf-8")) is not None


def test_a_hostile_title_round_trips_through_the_document(tmp_path: Path) -> None:
    """The check that makes the composed-markup guarantee load-bearing rather
    than decorative: the title is parsed back out of the serialized document
    and compared to what went in. The tooltip carries the id ahead of it, so
    the claim is that the title arrives whole and at the end of it."""
    document = _render([_claim("clm-hh1111", title=_HOSTILE_TITLE)])
    (tmp_path / "hostile.svg").write_text(document, encoding="utf-8", newline="\n")

    root = ET.fromstring((tmp_path / "hostile.svg").read_text(encoding="utf-8"))
    tooltip = _by_local(_node_groups(root)["clm-hh1111"], "title")[0].text
    assert tooltip.startswith("clm-hh1111")
    assert tooltip.endswith(_HOSTILE_TITLE)


def test_a_hostile_title_is_truncated_on_the_label_line_but_whole_in_the_tooltip() -> None:
    root = ET.fromstring(_render([_claim("clm-hh1111", title=_HOSTILE_TITLE)]))
    label = _by_local(_node_groups(root)["clm-hh1111"], "text")[1].text

    assert len(label) == style.LABEL_CHARS
    assert label.endswith(style.TRUNCATION_ELLIPSIS)
    assert _HOSTILE_TITLE.startswith(label[:-1])


def test_no_label_line_anywhere_in_the_golden_is_wider_than_the_box_it_sits_in() -> None:
    """The box is a width the labels fit, not one they usually fit.

    Every line is cut to the same cap, the id's included — a ``work-`` id is a
    citation key and is bounded by nothing, so an uncut line would run across
    its neighbour rather than overflow into its own padding.
    """
    root = ET.fromstring(MINI_KB_GOLDEN.read_text(encoding="utf-8"))
    lines = [text.text for group in _node_groups(root).values() for text in _by_local(group, "text")]

    assert lines
    assert max(len(line) for line in lines) <= style.LABEL_CHARS
    assert max(len(line) for line in lines) * style.CHAR_ADVANCE + 2 * style.BOX_PADDING_X <= style.BOX_WIDTH


def test_a_long_id_is_cut_to_the_box_and_read_back_whole_from_the_tooltip() -> None:
    """An id is not a bounded string. A minted one is ten characters and a
    framework one twelve, but a ``work-`` id is a citation key and the corpus
    carries them to 37 — this is that length. The cut is what keeps the line
    inside its box; the tooltip is what keeps the id recoverable from the sheet.

    ``mini-kb`` hosts no ``work-`` node, so this fixture is synthetic.
    """
    long_id = "work-Vershynin26-high-dim-probability"
    cut = long_id[: style.LABEL_CHARS - 1] + style.TRUNCATION_ELLIPSIS
    root = ET.fromstring(_render([_claim(long_id, title="A cited work")]))

    assert _by_local(_node_groups(root)[cut], "text")[0].text == cut
    assert _by_local(_node_groups(root)[cut], "title")[0].text.startswith(long_id)


def test_every_tooltip_opens_its_group_and_the_group_is_all_its_link_wraps() -> None:
    """The structural precondition the tooltip rests on, which no rendered
    picture shows and no rasteriser can be asked about: a ``title`` is its
    parent's where it opens that parent, and the group carrying it is the
    innermost element under the ``a``. Nested the other way up the tooltip would
    be the link's; the link contributes none of its own, an SVG ``a`` having no
    analogue of HTML's ``title`` attribute.

    Swept over the golden rather than one synthetic node, so every node kind the
    fixture carries is in it.
    """
    root = ET.fromstring(MINI_KB_GOLDEN.read_text(encoding="utf-8"))
    anchors = _by_local(root, "a")

    assert len(anchors) == 32
    for anchor in anchors:
        assert [_local(child.tag) for child in anchor] == ["g"]
        assert _local(list(anchor)[0][0].tag) == "title"


# ---------------------------------------------------------------------------
# Mechanically: no string literal in the package composes markup
# ---------------------------------------------------------------------------
#
# The guard lives here rather than inside the package it sweeps, so it cannot
# match its own source. Its teeth are demonstrated below against a copy of the
# package with a literal planted in it — a sweep nobody has watched fail is a
# sweep that may be reaching nothing.

_MARKUP_OPENER = "<"


def _markup_literals(package: Path) -> tuple[list[Path], dict[str, list[str]]]:
    """Every string literal under ``package`` that opens markup, by file.

    Takes the tree under test as a parameter so the planted-literal run
    exercises this same discovery, not a second implementation of it.
    """
    sources = sorted(package.rglob("*.py"))
    found: dict[str, list[str]] = {}
    for path in sources:
        tree = ast.parse(path.read_text(encoding="utf-8"))
        offenders = [
            node.value
            for node in ast.walk(tree)
            if isinstance(node, ast.Constant) and isinstance(node.value, str) and _MARKUP_OPENER in node.value
        ]
        if offenders:
            found[path.name] = offenders
    return sources, found


def test_no_string_literal_in_the_package_contains_a_markup_opener() -> None:
    """The document is composed by the element tree, the XML declaration
    included — a processing-instruction node emits that, so this rule has no
    exception to remember. A hand-rolled escaper is an exhaustiveness obligation
    with no mechanical check; this is the check that keeps one from appearing."""
    sources, found = _markup_literals(_PACKAGE)

    assert {path.name for path in sources} >= {"model.py", "layout.py", "style.py", "svg.py"}
    assert found == {}


def test_the_guard_fails_on_a_planted_literal(tmp_path: Path) -> None:
    """The teeth. The plant goes into a copy of the real package, so a guard that
    had stopped reaching the package's files would fail here too."""
    planted = tmp_path / "kb_graph"
    shutil.copytree(_PACKAGE, planted, ignore=shutil.ignore_patterns("__pycache__"))
    (planted / "svg.py").write_text(
        (planted / "svg.py").read_text(encoding="utf-8") + '\n_PLANTED = "<svg>"\n',
        encoding="utf-8",
        newline="\n",
    )

    sources, found = _markup_literals(planted)

    assert {path.name for path in sources} == {path.name for path in _PACKAGE.rglob("*.py")}
    assert found == {"svg.py": ["<svg>"]}


# ---------------------------------------------------------------------------
# The numeric contract
# ---------------------------------------------------------------------------

#: Every attribute whose value is geometry. ``viewBox`` carries four tokens and
#: ``points`` two per vertex, so the check splits on both separators the two use
#: and holds each token to the same rule. ``points`` is the one that would go
#: vacuous if it were left out: an edge's coordinates live nowhere else now that
#: a stroke is a chain rather than an ``x1``/``y1``/``x2``/``y2`` line.
_INTEGER_ATTRIBUTES = ("viewBox", "points", "width", "height", "x", "y", "stroke-width", "font-size")
_INTEGER = re.compile(r"^-?(0|[1-9][0-9]*)$")
_GEOMETRY_SEPARATOR = re.compile(r"[\s,]+")

#: The hop arc, the single non-integral geometry: every value three decimals,
#: and the sweep flag a constant because the bulge rule has no cases.
_ARC = re.compile(r"^M (-?\d+\.\d{3}) (-?\d+\.\d{3}) A (\d+\.\d{3}) (\d+\.\d{3}) 0 0 1 (-?\d+\.\d{3}) (-?\d+\.\d{3})$")


def test_every_emitted_coordinate_in_the_golden_is_an_integer() -> None:
    root = ET.fromstring(MINI_KB_GOLDEN.read_text(encoding="utf-8"))
    checked = 0
    for element in root.iter():
        for name in _INTEGER_ATTRIBUTES:
            value = element.get(name)
            if value is None:
                continue
            for token in _GEOMETRY_SEPARATOR.split(value):
                assert _INTEGER.match(token), f"{_local(element.tag)}/{name} is {value!r}"
                checked += 1
    assert checked > 0


def test_every_arc_value_in_the_golden_carries_exactly_three_decimals() -> None:
    arcs = [
        element.get("d") for element in _by_local(ET.fromstring(MINI_KB_GOLDEN.read_text(encoding="utf-8")), "path")
    ]

    assert arcs
    for data in arcs:
        assert _ARC.match(data), data


def test_the_number_formatter_rounds_once_and_never_emits_a_signed_zero() -> None:
    """The formatter is the single place rounding happens, applied at emission
    after all the arithmetic."""
    assert svg.format_number(-24) == "-24"
    assert svg.format_number(0) == "0"
    # A crossing point arrives as an exact Fraction, which is what makes the
    # rounding one act rather than an accumulation of intermediate ones.
    assert svg.format_number(Fraction(1, 3)) == "0.333"
    assert svg.format_number(Fraction(-1, 3)) == "-0.333"
    assert svg.format_number(-0.0001) == "0.000"


def test_every_hop_arc_bridges_toward_screen_up() -> None:
    """The bulge is a screen fact and not an edge-local one.

    A fixed rotation of the hopping edge's own direction has constant handedness
    *relative to that edge*, so it flips in screen terms whenever the edge does:
    every hop on a right-to-left edge dips downward instead of bridging. Ordering
    the arc's two endpoints by screen x first is what makes the one rule serve
    both — the arc always runs left to right, so the constant sweep flag always
    bulges it upward.

    Four premises and four dependents, every pair joined: a shape that carries
    crossings no in-layer order can remove, and — the point of *four* — crossings
    whose higher-key edge is one of the right-to-left ones.
    """
    low = [f"clm-ll000{n}" for n in range(4)]
    high = [f"clm-uu000{n}" for n in range(4)]
    sheet = _sheet([_claim(cid) for cid in (*low, *high)], [_edge(up, down) for up in high for down in low])

    segments = {edge.key: edge.segments for edge in sheet.edges}
    hopped = [segments[hop.hopping][hop.hopping_segment] for hop in sheet.hops]
    assert [
        segment for segment in hopped if segment.end.x < segment.start.x
    ], "the fixture must carry the case the ordering exists for"

    root = ET.fromstring(svg.render(sheet, link_base="."))
    arcs = [_ARC.match(element.get("d")) for element in _by_local(root, "path")]
    assert arcs and all(arcs)
    for arc in arcs:
        start_x, start_y, _, _, end_x, end_y = (float(group) for group in arc.groups())
        # Ordered by screen x, tie-broken by y — and the sweep flag the pattern
        # pins is what turns that into a bulge on the upper side of the chord.
        assert (start_x, start_y) < (end_x, end_y)


def test_a_crossing_draws_one_arc_on_the_higher_key_edge() -> None:
    """Two edges built to cross, at the markup level: the glyph is centred on the
    crossing point and its endpoints sit one hop radius either side along the
    hopping edge. Which way it bulges from there is the test above.

    Every pair is joined, so the crossing is one the in-layer sweep cannot
    remove — a hand-built reversal is what the sweep is for.
    """
    left, right = "clm-aa0001", "clm-aa0002"
    upper_left, upper_right = "clm-bb0001", "clm-bb0002"
    sheet = _sheet(
        [_claim(cid) for cid in (left, right, upper_left, upper_right)],
        [_edge(upper, lower) for upper in (upper_left, upper_right) for lower in (left, right)],
    )
    assert len(sheet.hops) == 1

    root = ET.fromstring(svg.render(sheet, link_base="kb-root"))
    arcs = _by_local(root, "path")
    assert len(arcs) == 1

    hop = sheet.hops[0]
    match = _ARC.match(arcs[0].get("d"))
    assert match, arcs[0].get("d")
    start_x, start_y, radius, _, end_x, end_y = (float(group) for group in match.groups())
    assert radius == float(style.HOP_RADIUS)
    # The chord's midpoint is the crossing point, and its half-length the radius.
    assert (start_x + end_x) / 2 == pytest.approx(float(hop.x))
    assert (start_y + end_y) / 2 == pytest.approx(float(hop.y))
    # Three decimals per endpoint is the whole tolerance here: the arithmetic is
    # exact until the formatter, and the formatter is the only thing rounding.
    assert ((end_x - start_x) ** 2 + (end_y - start_y) ** 2) ** 0.5 == pytest.approx(2 * style.HOP_RADIUS, abs=0.002)
    # The arc is drawn on the hopping edge, in the hopping edge's own colour.
    assert arcs[0].get("stroke") == _edge_lines(root)[hop.hopping].get("stroke")


# ---------------------------------------------------------------------------
# Hyperlinks
# ---------------------------------------------------------------------------


def test_a_link_base_is_computed_with_pure_posix_paths_and_walks_up_where_it_must() -> None:
    base = svg.relative_link_base(kb_root="a/kb-root", sheet_dir="a/build/graphs")
    assert base == PurePosixPath("../../kb-root")
    assert svg.relative_link_base(kb_root="kb-root", sheet_dir="") == PurePosixPath("kb-root")
    assert svg.relative_link_base(kb_root="a/b", sheet_dir="a/b") == PurePosixPath(".")


def test_a_link_base_refuses_a_pair_with_no_relative_answer() -> None:
    with pytest.raises(ValueError, match="absolute or both relative"):
        svg.relative_link_base(kb_root="/elsewhere/kb-root", sheet_dir="build/graphs")


def test_a_node_links_to_the_kb_markdown_the_index_names() -> None:
    root = ET.fromstring(_render([_claim("clm-aa1111", anchor="proposition-4-3")], link_base="../../kb-root"))
    assert _hrefs(root) == {"clm-aa1111": "../../kb-root/vol1/topic/leaf.md#proposition-4-3"}


def test_an_empty_canonical_anchor_yields_a_path_with_no_fragment() -> None:
    """The index emits an empty anchor in one branch and ``mini-kb`` has no
    instance of it, so this fixture is synthetic."""
    root = ET.fromstring(_render([_claim("clm-aa1111", anchor="")], link_base="kb-root"))
    assert _hrefs(root) == {"clm-aa1111": "kb-root/vol1/topic/leaf.md"}


def test_a_stub_carries_no_link_at_all() -> None:
    """A ghost id has no record, so there is no definition for a link to name."""
    root = ET.fromstring(_render([_claim("clm-aa1111")], [_edge("clm-aa1111", "clm-ghost")]))
    assert set(_hrefs(root)) == {"clm-aa1111"}
    assert set(_node_groups(root)) == {"clm-aa1111", "clm-ghost"}


def test_every_golden_link_resolves_from_the_sheets_own_directory_to_a_file_on_disk() -> None:
    """The whole claim, end to end: the golden's own directory plus the ``href``
    it emitted lands on the committed fixture's Markdown."""
    root = ET.fromstring(MINI_KB_GOLDEN.read_text(encoding="utf-8"))
    hrefs = _hrefs(root)

    assert len(hrefs) == 32
    for node_id, href in sorted(hrefs.items()):
        path, _, anchor = href.partition("#")
        assert anchor, node_id  # mini-kb carries no empty anchor; the synthetic fixture covers that
        assert (MINI_KB_GOLDEN.parent / path).resolve().is_file(), href


# ---------------------------------------------------------------------------
# Colour — all four node types and the framework-target edge
# ---------------------------------------------------------------------------


def test_all_four_node_types_take_their_own_fill() -> None:
    claim, support, experiment, invariant, axiom = (
        _claim("clm-aa1111"),
        _support("sup-aa1111"),
        _experiment("exp-aa1111"),
        _framework("INVARIANT-S1"),
        _framework("axiom-1", "axiom"),
    )
    root = ET.fromstring(_render([claim, support, experiment, invariant, axiom]))
    fills = {node_id: _by_local(group, "rect")[0].get("fill") for node_id, group in _node_groups(root).items()}

    assert fills == {
        "clm-aa1111": style.BAND_PALETTE["ok-to-build"],
        "sup-aa1111": style.BAND_PALETTE["do-not-build"],
        "exp-aa1111": style.EXPERIMENT_FILL,
        "INVARIANT-S1": style.FRAMEWORK_FILL,
        "axiom-1": style.FRAMEWORK_FILL,
    }
    # A framework fill is deliberately not a rung of the ramp: bedrock is a
    # convention of the solidity rule, not a stored score.
    assert style.FRAMEWORK_FILL not in style.BAND_PALETTE.values()


def test_an_experiment_carries_its_status_as_a_word_rather_than_a_score() -> None:
    """The status is still shown and still never asserted as a score — it rides
    the tooltip rather than the id line, which is the one line on the box a
    reader carries off to a register or a query."""
    root = ET.fromstring(_render([_experiment("exp-aa1111")]))
    group = _node_groups(root)["exp-aa1111"]

    assert _by_local(group, "text")[0].text == "exp-aa1111"
    assert _by_local(group, "title")[0].text == "exp-aa1111 · run — An experiment"


def test_a_depends_edge_onto_a_framework_node_takes_the_ladders_top_rung() -> None:
    """Framework dependencies contribute 1.0 and never pend, so the edge shows
    the top rung while the node itself shows no rung at all."""
    root = ET.fromstring(
        _render(
            [_claim("clm-aa1111"), _framework("INVARIANT-S1")],
            [_edge("clm-aa1111", "INVARIANT-S1", target_kind="invariant")],
        )
    )
    stroke = _edge_lines(root)[("clm-aa1111", "INVARIANT-S1")].get("stroke")

    assert stroke == style.FRAMEWORK_EDGE_COLOUR
    assert stroke == style.BAND_PALETTE[kb_schema.BUILD_BAND_LADDER[0].slug]


def test_a_depends_edge_onto_a_claim_takes_the_premises_own_band() -> None:
    """A weak premise's fan-out reads weak at every dependent — instrument role 2."""
    root = ET.fromstring(
        _render(
            [_claim("clm-aa1111"), _claim("clm-bb2222", band="do-not-build")],
            [_edge("clm-aa1111", "clm-bb2222")],
        )
    )
    assert _edge_lines(root)[("clm-aa1111", "clm-bb2222")].get("stroke") == style.BAND_PALETTE["do-not-build"]


@pytest.mark.parametrize(
    ("overrides", "expected"),
    [
        ({"relation": "supports", "fraction": 1.0}, "ok-to-build"),
        ({"relation": "supports", "fraction": 0.3}, "do-not-build"),
        ({"relation": "strengthens", "strength": 0.7}, "ok-with-caveats"),
    ],
    ids=["supports-full", "supports-thin", "strengthens"],
)
def test_a_supports_or_strengthens_edge_takes_the_band_of_its_own_value(overrides: dict, expected: str) -> None:
    root = ET.fromstring(
        _render(
            [_claim("clm-aa1111"), _claim("clm-bb2222", band="refuted")],
            [_edge("clm-aa1111", "clm-bb2222", **overrides)],
        )
    )
    assert _edge_lines(root)[("clm-aa1111", "clm-bb2222")].get("stroke") == style.BAND_PALETTE[expected]


def test_a_pending_fraction_is_a_colour_and_never_a_dash() -> None:
    """``fraction: "*pending*"`` is off-ladder neutral; dashes are the defect
    channel alone. The literal is recognised by not being a number, so no
    typed-out string is compared against."""
    root = ET.fromstring(
        _render(
            [_claim("clm-aa1111"), _claim("clm-bb2222")],
            [_edge("clm-aa1111", "clm-bb2222", relation="supports", fraction="*pending*")],
        )
    )
    line = _edge_lines(root)[("clm-aa1111", "clm-bb2222")]

    assert line.get("stroke") == style.PENDING_FILL
    assert line.get("stroke-dasharray") is None


def test_a_reference_is_drawn_off_the_ramp_and_at_half_weight() -> None:
    """A reference asserts nothing about strength, so it takes no rung — and not
    the neutral either, which is what a *pending* dependency already takes."""
    root = ET.fromstring(
        _render(
            [_claim("clm-aa1111"), _claim("clm-bb2222")],
            [_edge("clm-aa1111", "clm-bb2222", relation="references")],
        )
    )
    line = _edge_lines(root)[("clm-aa1111", "clm-bb2222")]

    assert line.get("stroke") == style.REFERENCE_EDGE_COLOUR
    assert line.get("stroke") not in {*style.BAND_PALETTE.values(), style.PENDING_FILL}
    assert line.get("stroke-width") == str(style.REFERENCE_STROKE_WIDTH) != str(style.EDGE_STROKE_WIDTH)
    # Dash stays the defect channel.
    assert line.get("stroke-dasharray") is None


def test_two_claims_naming_each_other_draw_as_two_ordinary_strokes() -> None:
    """A mutual reference is the author's argument, not a cycle: no back edge.

    The counterfactual is the assertion's other half — the same pair read as
    ``depends`` is a cycle, and both strokes take the back-edge dash.
    """
    nodes = [_claim("clm-aa1111"), _claim("clm-bb2222")]
    mutual = [("clm-aa1111", "clm-bb2222"), ("clm-bb2222", "clm-aa1111")]

    root = ET.fromstring(_render(nodes, [_edge(*pair, relation="references") for pair in mutual]))
    lines = _edge_lines(root)
    assert set(lines) == set(mutual)
    assert {line.get("stroke-dasharray") for line in lines.values()} == {None}

    depending = ET.fromstring(_render(nodes, [_edge(*pair) for pair in mutual]))
    assert {line.get("stroke-dasharray") for line in _edge_lines(depending).values()} == {style.DASH_BACK_EDGE}


def test_an_edge_to_a_ghost_id_takes_the_stub_style_and_no_band() -> None:
    root = ET.fromstring(_render([_claim("clm-aa1111")], [_edge("clm-aa1111", "clm-ghost")]))
    line = _edge_lines(root)[("clm-aa1111", "clm-ghost")]

    assert (line.get("stroke"), line.get("stroke-dasharray")) == (style.STUB_STROKE, style.DASH_STUB)
    assert _by_local(_node_groups(root)["clm-ghost"], "title") == []


def test_a_relation_conflict_draws_one_stroke_carrying_the_mark_and_naming_both() -> None:
    root = ET.fromstring(
        _render(
            [_claim("clm-aa1111"), _claim("clm-bb2222")],
            [
                _edge("clm-aa1111", "clm-bb2222"),
                _edge("clm-aa1111", "clm-bb2222", relation="supports", fraction=1.0),
            ],
        )
    )
    lines = _edge_lines(root)

    assert len(lines) == 1
    line = lines[("clm-aa1111", "clm-bb2222")]
    assert line.get("stroke") == style.CONFLICT_STROKE
    assert _by_local(line, "title")[0].text == "clm-aa1111 → clm-bb2222 — relations: depends, supports"


def test_a_deduped_strokes_tooltip_merges_its_contexts_and_stands_alone_without_them() -> None:
    root = ET.fromstring(
        _render(
            [_claim("clm-aa1111"), _claim("clm-bb2222"), _claim("clm-cc3333")],
            [
                _edge("clm-aa1111", "clm-bb2222", context="step 2"),
                _edge("clm-aa1111", "clm-bb2222", context="step 1"),
                _edge("clm-aa1111", "clm-cc3333"),
            ],
        )
    )
    titles = {pair: _by_local(line, "title")[0].text for pair, line in _edge_lines(root).items()}

    assert titles[("clm-aa1111", "clm-bb2222")] == "clm-aa1111 → clm-bb2222 — step 1 · step 2"
    assert titles[("clm-aa1111", "clm-cc3333")] == "clm-aa1111 → clm-cc3333"


def test_a_foreign_neighbour_draws_outline_only() -> None:
    """The one-hop neighbour on a domain sheet — the caller's selection, this
    module's style."""
    root = ET.fromstring(_render([_claim("clm-aa1111"), _claim("clm-bb2222")], foreign=["clm-bb2222"]))
    fills = {node_id: _by_local(group, "rect")[0].get("fill") for node_id, group in _node_groups(root).items()}

    assert fills["clm-bb2222"] == style.FOREIGN_FILL
    assert fills["clm-aa1111"] == style.BAND_PALETTE["ok-to-build"]


# ---------------------------------------------------------------------------
# Structure the rest of the ladder leans on
# ---------------------------------------------------------------------------


def test_the_root_declares_the_namespace_as_a_plain_attribute_and_pins_its_font() -> None:
    """The trap the composed-markup rule guards against: a namespaced tree
    serializes every tag with an ``ns0:`` prefix. Read from the raw text,
    because a parser resolves the declaration away."""
    document = _render([_claim("clm-aa1111")])

    assert "ns0" not in document
    assert 'xmlns="http://www.w3.org/2000/svg"' in document
    root = ET.fromstring(document)
    assert root.get("font-family") == style.FONT_FAMILY
    assert root.get("font-size") == str(style.FONT_SIZE)


def test_the_draw_order_is_edges_then_hops_then_boxes() -> None:
    """An edge crossing layers is routed through a dummy column in each, so the
    draw order settles what routing does not: a stroke meeting a box passes
    under it, which is the schematic reading and costs nothing."""
    root = ET.fromstring(_render([_claim("clm-aa1111"), _claim("clm-bb2222")], [_edge("clm-bb2222", "clm-aa1111")]))
    groups = [element.get("class") for element in root if _local(element.tag) == "g"]

    assert groups == ["edges", "hops", "nodes"]


def test_an_edge_across_layers_is_one_polyline_and_its_dummy_is_never_drawn() -> None:
    """The chain is one element carrying every vertex, and the placeholders it
    bends at have no box, no label and no link — they are columns, not nodes.

    ``fill`` is none because a polyline's default fill closes the path: a
    three-point chain would otherwise paint the triangle under itself.
    """
    top, middle, bottom = "clm-aa0001", "clm-mm0001", "clm-bb0001"
    root = ET.fromstring(
        _render(
            [_claim(cid) for cid in (top, middle, bottom)],
            [_edge(middle, bottom), _edge(top, middle), _edge(top, bottom)],
        )
    )
    strokes = _edge_lines(root)

    assert len(strokes) == 3
    vertices = {pair: len(stroke.get("points").split()) for pair, stroke in strokes.items()}
    assert vertices == {(middle, bottom): 2, (top, middle): 2, (top, bottom): 3}
    assert strokes[(top, bottom)].get("fill") == "none"
    # Three boxes, three labels' worth of groups, three links: nothing was drawn
    # for the dummy the spanning stroke bends at.
    assert set(_node_groups(root)) == {top, middle, bottom}
    assert set(_hrefs(root)) == {top, middle, bottom}


def test_the_view_box_is_the_only_global_quantity_and_the_root_pins_no_size() -> None:
    """The frame is the ``viewBox``, and a pinned ``width``/``height`` is not part of it.

    Those two are the intrinsic size a viewer lays the document out at, so a
    real corpus's sheet — some fifteen thousand pixels wide — opened at that
    size and could only be zoomed *in* from there. The ``viewBox`` alone carries
    everything a viewer needs to fit it to a window.
    """
    sheet = _sheet([_claim("clm-aa1111")])
    box = sheet.view_box
    root = ET.fromstring(svg.render(sheet, link_base="kb-root"))

    assert root.get("viewBox") == f"{box.min_x} {box.min_y} {box.width} {box.height}"
    assert (root.get("width"), root.get("height")) == (None, None)
    # The background still paints the whole sheet, so a container's own colour
    # never shows through the picture.
    background = _by_local(root, "rect")[0]
    assert background.get("class") == "sheet"
    assert (background.get("width"), background.get("height")) == (str(box.width), str(box.height))
